OrdererOrgs:
  - Name: SuperOrderer
    Domain: example.com
    Specs:
      - Hostname: SuperOrderer

PeerOrgs:
  - Name: GatewayOrg
    Domain: GatewayOrg.example.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2

  - Name: UserOrg
    Domain: UserOrg.example.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2

  - Name: ServiceOrg
    Domain: ServiceOrg.example.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2
    
